eureka:
  instance:
    preferIpAddress: true
    ipAddress: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: foo
  profiles:
    active: dev,development

server:
  port: 9999
